// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkYNyuxPHEX9Zz6KbuFe7HMtGBI_ian0',
    appId: '1:652343286066:web:a546e1a5e50ec897ab1f2b',
    messagingSenderId: '652343286066',
    projectId: 'blueexchangeproject',
    authDomain: 'blueexchangeproject.firebaseapp.com',
    storageBucket: 'blueexchangeproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK4oPseDH6yM7gXyTfDDsW20tenIeDalM',
    appId: '1:652343286066:android:08bbf36b05e140efab1f2b',
    messagingSenderId: '652343286066',
    projectId: 'blueexchangeproject',
    storageBucket: 'blueexchangeproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1oaUUV4ouLKISXUuMij4YxVHAhrqduI',
    appId: '1:652343286066:ios:50ced0f8ec988f89ab1f2b',
    messagingSenderId: '652343286066',
    projectId: 'blueexchangeproject',
    storageBucket: 'blueexchangeproject.firebasestorage.app',
    iosBundleId: 'com.example.blueexchangeproject',
  );

}